<?php

return [
    // Central list for guest reservation UX (ISO 3166-1 alpha-2 codes + XK + OTHER).
    // Labels are localized per locale key (cg/en).
    'ME' => ['cg' => 'Crna Gora', 'en' => 'Montenegro'],
    'HR' => ['cg' => 'Hrvatska', 'en' => 'Croatia'],
    'RS' => ['cg' => 'Srbija', 'en' => 'Serbia'],
    'BA' => ['cg' => 'Bosna i Hercegovina', 'en' => 'Bosnia and Herzegovina'],
    'MK' => ['cg' => 'Sjeverna Makedonija', 'en' => 'North Macedonia'],
    'SI' => ['cg' => 'Slovenija', 'en' => 'Slovenia'],
    'AL' => ['cg' => 'Albanija', 'en' => 'Albania'],
    'AD' => ['cg' => 'Andora', 'en' => 'Andorra'],
    'AT' => ['cg' => 'Austrija', 'en' => 'Austria'],
    'BY' => ['cg' => 'Bjelorusija', 'en' => 'Belarus'],
    'BE' => ['cg' => 'Belgija', 'en' => 'Belgium'],
    'BG' => ['cg' => 'Bugarska', 'en' => 'Bulgaria'],
    'CH' => ['cg' => 'Švajcarska', 'en' => 'Switzerland'],
    'CZ' => ['cg' => 'Češka', 'en' => 'Czechia'],
    'DE' => ['cg' => 'Njemačka', 'en' => 'Germany'],
    'DK' => ['cg' => 'Danska', 'en' => 'Denmark'],
    'EE' => ['cg' => 'Estonija', 'en' => 'Estonia'],
    'ES' => ['cg' => 'Španija', 'en' => 'Spain'],
    'FI' => ['cg' => 'Finska', 'en' => 'Finland'],
    'FR' => ['cg' => 'Francuska', 'en' => 'France'],
    'GB' => ['cg' => 'Ujedinjeno Kraljevstvo', 'en' => 'United Kingdom'],
    'GR' => ['cg' => 'Grčka', 'en' => 'Greece'],
    'HU' => ['cg' => 'Mađarska', 'en' => 'Hungary'],
    'IE' => ['cg' => 'Irska', 'en' => 'Ireland'],
    'IL' => ['cg' => 'Izrael', 'en' => 'Israel'],
    'IS' => ['cg' => 'Island', 'en' => 'Iceland'],
    'IT' => ['cg' => 'Italija', 'en' => 'Italy'],
    'LI' => ['cg' => 'Lihtenštajn', 'en' => 'Liechtenstein'],
    'LT' => ['cg' => 'Litvanija', 'en' => 'Lithuania'],
    'LU' => ['cg' => 'Luksemburg', 'en' => 'Luxembourg'],
    'LV' => ['cg' => 'Letonija', 'en' => 'Latvia'],
    'MC' => ['cg' => 'Monako', 'en' => 'Monaco'],
    'MD' => ['cg' => 'Moldavija', 'en' => 'Moldova'],
    'MT' => ['cg' => 'Malta', 'en' => 'Malta'],
    'NL' => ['cg' => 'Holandija', 'en' => 'Netherlands'],
    'NO' => ['cg' => 'Norveška', 'en' => 'Norway'],
    'PL' => ['cg' => 'Poljska', 'en' => 'Poland'],
    'PT' => ['cg' => 'Portugal', 'en' => 'Portugal'],
    'RO' => ['cg' => 'Rumunija', 'en' => 'Romania'],
    'RU' => ['cg' => 'Rusija', 'en' => 'Russia'],
    'SE' => ['cg' => 'Švedska', 'en' => 'Sweden'],
    'SK' => ['cg' => 'Slovačka', 'en' => 'Slovakia'],
    'SM' => ['cg' => 'San Marino', 'en' => 'San Marino'],
    'TR' => ['cg' => 'Turska', 'en' => 'Turkey'],
    'UA' => ['cg' => 'Ukrajina', 'en' => 'Ukraine'],
    'VA' => ['cg' => 'Vatikan', 'en' => 'Vatican City'],
    'XK' => ['cg' => 'Kosovo', 'en' => 'Kosovo'],
    'OTHER' => ['cg' => 'Ostalo', 'en' => 'Other'],
];

